---
apiVersion: v1
kind: Service
metadata:
  name: openliberty-service
  labels:
    app: openliberty-app
spec:
  selector:
    app: openliberty-app
  ports:
  - name: http
    protocol: TCP
    port: 80       # Port exposed by the service
    targetPort: 9080  # Port exposed by the container
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443      # Port exposed by the service for HTTPS
    targetPort: 9443  # Port exposed by the container
    nodePort: 30443
  type: NodePort  # Change to NodePort or ClusterIP if not using a cloud provider

